[project]
name = "alertmanager-tg-sender-adapter"
version = "2.0.3"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Danila Epishev", email = "DEpishev@alfabank.ru" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.3",
    "playwright>=1.60.0",
    "prometheus-client>=0.25.0",
    "prometheus-fastapi-instrumentator>=8.0.0",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "urllib3>=2.7.0",
    "uvicorn>=0.48.0",
]
[project.scripts]
alertmanager-tg-sender-adapter = "alertmanager_tg_sender_adapter.main:main"

[build-system]
requires = ["setuptools>=82.0.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[dependency-groups]
dev = [
    "ruff>=0.16.4",
    "ty>=0.0.73",
]
